BUILD_ALL=y
BUILD_SRC=$(BUILD_ALL)
BUILD_BENCHMARKS=$(BUILD_ALL)
BUILD_EXAMPLES=$(BUILD_ALL)
BUILD_TESTS=$(BUILD_ALL)
BUILD_DOCS=n
BUILD_STATIC=n
BUILD_SHARED=y
BUILD_DEBUG=n
BUILD_SAMLL=n
BUILD_STRICT=n

ifeq ($(BUILD_DEBUG),y)
BUILD_OPT_CFLAGS  = -O0 -g -DDEBUG -D_DEBUG
BUILD_OPT_LDFLAGS = -O0 -g
else
ifeq ($(BUILD_SMALL),y)
BUILD_OPT_CFLAGS  = -Os -DDBG_LEVEL=3
BUILD_OPT_LDFLAGS = -Os
else
BUILD_OPT_CFLAGS  = -O2 -g -DDBG_LEVEL=3
BUILD_OPT_LDFLAGS = -O2 -g
endif
endif

ifneq ($(BUILD_STRICT),y)
BUILD_OPT_CFLAGS += \
	-Wno-unused-function \
	-Wno-unused-variable \
	-Wno-unused-result \
	-Wno-unused-but-set-variable
else
BUILD_OPT_CFLAGS += \
	-Wall \
	-Werror
endif
