// XPR_ARP
#undef HAVE_XPR_ARP

// XPR_ARR
#define HAVE_XPR_ARR 1

// XPR_AVFRAME
#define HAVE_XPR_AVFRAME 1

// XPR_BASE64
#define HAVE_XPR_BASE64 1

// XPR_BITVECTOR
#define HAVE_XPR_BITVECTOR 1

// XPR_DEVCAPS
#undef HAVE_XPR_DEVCAPS

// XPR_DPU
#undef HAVE_XPR_DPU

// XPR_DPU_DRIVER_A2SVIDEO
#undef HAVE_XPR_DPU_DRIVER_A2SVIDEO

// XPR_DPU_DRIVER_A5SVIDEO
#undef HAVE_XPR_DPU_DRIVER_A5SVIDEO

// XPR_DPU_DRIVER_A5SYUV
#undef HAVE_XPR_DPU_DRIVER_A5SYUV

// XPR_DPU_DRIVER_ALL
#undef HAVE_XPR_DPU_DRIVER_ALL

// XPR_DPU_DRIVER_ALSAPCM
#undef HAVE_XPR_DPU_DRIVER_ALSAPCM

// XPR_DPU_DRIVER_G711TEST
#undef HAVE_XPR_DPU_DRIVER_G711TEST

// XPR_DPU_DRIVER_MDSD
#undef HAVE_XPR_DPU_DRIVER_MDSD

// XPR_DPU_DRIVER_PCMTEST
#undef HAVE_XPR_DPU_DRIVER_PCMTEST

// XPR_DRM
#undef HAVE_XPR_DRM

// XPR_DRM_DRIVER_ALL
#undef HAVE_XPR_DRM_DRIVER_ALL

// XPR_DRM_DRIVER_ALPUC_016
#undef HAVE_XPR_DRM_DRIVER_ALPUC_016

// XPR_DRM_DRIVER_DS18B20
#undef HAVE_XPR_DRM_DRIVER_DS18B20

// XPR_DRM_DRIVER_RECONBALL
#undef HAVE_XPR_DRM_DRIVER_RECONBALL

// XPR_FIFO
#define HAVE_XPR_FIFO 1

// XPR_FILE
#define HAVE_XPR_FILE 1

// XPR_GPIO
#undef HAVE_XPR_GPIO

// XPR_GPIO_DRIVER_A5S
#undef HAVE_XPR_GPIO_DRIVER_A5S

// XPR_GPIO_DRIVER_ALL
#undef HAVE_XPR_GPIO_DRIVER_ALL

// XPR_H264
#define HAVE_XPR_H264 1

// XPR_ICMP
#define HAVE_XPR_ICMP 1

// XPR_JSON
#define HAVE_XPR_JSON 1

// XPR_MD5
#define HAVE_XPR_MD5 1

// XPR_MCDEC
#define XPR_MCDEC 1
#define XPR_MCDEC_DRIVER_LIBAV 1

// XPR_MEM
#define HAVE_XPR_MEM 1

// XPR_PES
#define HAVE_XPR_PES 1

// XPR_PLUGIN
#define HAVE_XPR_PLUGIN 1

// XPR_RTSP
#define HAVE_XPR_RTSP 1

// XPR_RTSP_SERVER
#define HAVE_XPR_RTSP_SERVER 1

// XPR_RTSP_DRIVER_LIVE
#define HAVE_XPR_RTSP_DRIVER_LIVE 1

// XPR_SHA1
#define HAVE_XPR_SHA1 1

// XPR_STREAMBLOCK
#define HAVE_XPR_STREAMBLOCK 1

// XPR_SYNC
#define HAVE_XPR_SYNC 1

// XPR_SYS
#define HAVE_XPR_SYS 1

// XPR_THREAD
#define HAVE_XPR_THREAD 1

// XPR_UPS
#undef HAVE_XPR_UPS

// XPR_URL
#define HAVE_XPR_URL 1

// XPR_UTILS
#define HAVE_XPR_UTILS 1

// XPR_XML
#define HAVE_XPR_XML 1